### ISSUE TITLE
Mapbox & Crashlytics cause crash on AVD

### ISSUE THREAD

**Issue by wendt88** [nativescript-community/ui-mapbox#21]
## How to reproduce
Run:
1. `ns create test --vue`
2. `cd test`
3. `tns plugin add @nativescript/firebase` -> enable android and crashlytics only or copy `firebase.nativescript.json` below
4. `ns plugin add @nativescript-community/ui-mapbox`

copy [`google-services.json`](https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/master/demo-vue/app/App_Resources/Android/google-services.json) to your `App_Resources/Android` and change the app id to `org.nativescript.firebasedemo.firestore` or generate a new one fro your app id.

### firebase.nativescript.json:
```
{
    "using_ios": false,
    "using_android": true,
    "analytics": false,
    "firestore": false,
    "realtimedb": false,
    "authentication": false,
    "remote_config": false,
    "performance_monitoring": false,
    "external_push_client_only": false,
    "messaging": false,
    "in_app_messaging": false,
    "crashlytics": true,
    "storage": false,
    "functions": false,
    "facebook_auth": false,
    "google_auth": false,
    "admob": false,
    "dynamic_links": false,
    "ml_kit": false
}
```
### Run on AVD:
`ns debug android`

```
An uncaught Exception occurred on "com.google.firebase.crashlytics.startup1" thread.
null

StackTrace:
java.lang.ExceptionInInitializerError
	at okhttp3.internal.platform.Platform.get(Platform.java:85)
	at okhttp3.OkHttpClient.newSslSocketFactory(OkHttpClient.java:263)
	at okhttp3.OkHttpClient.<init>(OkHttpClient.java:229)
	at okhttp3.OkHttpClient.<init>(OkHttpClient.java:202)
	at com.google.firebase.crashlytics.internal.network.HttpRequest.<clinit>(HttpRequest.java:43)
	at com.google.firebase.crashlytics.internal.network.HttpRequestFactory.buildHttpRequest(HttpRequestFactory.java:43)
	at com.google.firebase.crashlytics.internal.common.AbstractSpiCall.getHttpRequest(AbstractSpiCall.java:113)
	at com.google.firebase.crashlytics.internal.settings.network.DefaultSettingsSpiCall.invoke(DefaultSettingsSpiCall.java:80)
	at com.google.firebase.crashlytics.internal.settings.SettingsController$1.then(SettingsController.java:200)
	at com.google.firebase.crashlytics.internal.settings.SettingsController$1.then(SettingsController.java:193)
	at com.google.android.gms.tasks.zzp.run(Unknown Source:2)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at com.google.firebase.crashlytics.internal.common.ExecutorUtils$1$1.onRun(ExecutorUtils.java:60)
	at com.google.firebase.crashlytics.internal.common.BackgroundPriorityRunnable.run(BackgroundPriorityRunnable.java:27)
	at java.lang.Thread.run(Thread.java:923)
Caused by: java.lang.IllegalStateException: Expected Android API level 21+ but was 30
	at okhttp3.internal.platform.AndroidPlatform.buildIfSupported(AndroidPlatform.java:238)
	at okhttp3.internal.platform.Platform.findPlatform(Platform.java:202)
	at okhttp3.internal.platform.Platform.<clinit>(Platform.java:79)
	... 16 more
```

read [this okhttp issue](https://github.com/square/okhttp/issues/5816) and tried tu use a newer version of `okHttp` without success, by adding:
```
ext {
    okHttpVersion = "3.14.7"
}
```

is there anything wrong, or something i can do?

**Comment by Hugheym** [comment]
Had a similar issue. Upgrading com.squareup.okhttp3:**logging-interceptor** solved the problem for me.

**Comment by wendt88** [comment]
@Hugheym can you help me how? 

my `before-plugins.gradle` contains (for firebase push notifications & geolocation):
```
android {  
  project.ext {
    googlePlayServicesVersion = "+"
  }
}
```

THX

**Comment by Hugheym** [comment]
Hey, sorry, I was speaking from experience on another Mapbox project. I'm not very familiar with native script, but can't find where okHttpVersion gets used... https://github.com/nativescript-community/ui-mapbox/blob/master/plugin/platforms/android/include.gradle

Since okHttp is a transitive dependency via many of the mapbox dependencies you're using, I'd update those. If possible, start with mapboxTelemetryVersion , mapboxPluginsVersion , mapboxAnnotationPluginVersion , mapboxGesturesVersion to see if it'll solve the problem since they are the least likely to have large changes. 

```
ext {
    def mapboxVersion =  "8.6.6"
    def mapboxTelemetryVersion =  "6.1.0" 
    def mapboxPluginsVersion =  "v9" 
    def mapboxAnnotationPluginVersion =  "0.9.0"
    def mapboxGesturesVersion =  "0.7.0"
}
```

**Comment by wendt88** [comment]
@jameszonk it works fine, thx!

**Comment by Reached** [comment]
@ghost thanks for providing the solution! 

However I don't think it's related to the mentioned plugin (Crashlytics), as I am not using that in my project, and it still crashed on Android. After adding the logging dependency, it worked like a charm however :)
