### ISSUE TITLE
XCODE 12.2 iOS build Error code 65

### ISSUE THREAD

**Issue by jameszonk** [nativescript-community/ui-mapbox#3]
When I add the plugin I get exit `Error is: Command xcodebuild failed with exit code 65.`

- "XCODE 12.2, XCODE 12.1"
- "@nativescript:": "7.0.11"
-  "@nativescript/core": "7.0.13",
-   "@nativescript/ios": "7.0.5",

**Comment by farfromrefug** [comment]
@jameszonk will need more than that :D
A full log will help. Also did you read this https://github.com/nativescript-community/ui-mapbox#warning

**Comment by SKTAR** [comment]
Same problem here , this is the error message after  running on IOS simulater 14.0

> **ns run ios --log trace ** 


> Error: Command xcodebuild failed with exit code 65
>       at Errors.failWithOptions (/usr/local/lib/node_modules/nativescript/lib/common/errors.js:157:27)
>       at Errors.fail (/usr/local/lib/node_modules/nativescript/lib/common/errors.js:130:21)
>       at XcodebuildCommandService.<anonymous> (/usr/local/lib/node_modules/nativescript/lib/services/ios/xcodebuild-command-service.js:34:30)
>       at Generator.throw (<anonymous>)
>       at rejected (/usr/local/lib/node_modules/nativescript/lib/services/ios/xcodebuild-command-service.js:6:65)
>       at processTicksAndRejections (internal/process/task_queues.js:97:5) {
>     name: 'Exception',
>     errorCode: 127,
>     suggestCommandHelp: false,
>     proxyAuthenticationRequired: false,
>     printOnStdout: undefined
>   }



after removing  ui-mapbox plugin. it's working.

 I have no idea how to fix this , anyone can help me please ?.

**Comment by farfromrefug** [comment]
@SKTAR sorry but still.not enough. Can you share the full build log?

**Comment by SKTAR** [comment]
@farfromrefug    Here is a full log file , Thank a lot
[log_trace_map_box_ios.txt](https://github.com/nativescript-community/ui-mapbox/files/5582882/log_trace_map_box_ios.txt)

**Comment by farfromrefug** [comment]
@shirakaba this is your issue 
```
Undefined symbols for architecture i386:
  "_OBJC_CLASS_$_Config", referenced from:
      objc-class-ref in main.o
  "_OBJC_CLASS_$_NativeScript", referenced from:
      objc-class-ref in main.o
     (maybe you meant: _OBJC_CLASS_$_NativeScriptEmbedder)
  "_TNSInitializeLiveSync", referenced from:
      _main in main.o
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
You are using latest mapbox 6.x?
I think the error comes from their new build system. either fix the version to 5.x([see here](https://github.com/nativescript-community/ui-mapbox#warning)) or go and ask them on their repo (search first).
Nothing i can do really.

**Comment by mrwrighty** [comment]
Any update on this. Getting same error. ns doctor reports

✔ Component nativescript has 7.1.2 version and is up to date.
✔ Component @nativescript/core has 7.1.4 version and is up to date.
✔ Component @nativescript/ios has 7.1.1 version and is up to date.

MapBox plugin version @nativescript-community/ui-mapbox   ^6.2.0

**Comment by farfromrefug** [comment]
@mrwrighty please share the build log

**Comment by mrwrighty** [comment]
Undefined symbols for architecture i386:
  "_OBJC_CLASS_$_DDASLLogger", referenced from:
      objc-class-ref in TSLocationManager(TSLog.o)
  "_OBJC_IVAR_$_DDLogMessage._timestamp", referenced from:
      -[TSDBLogEntry initWithLogMessage:] in TSLocationManager(TSDBLogger.o)
  "_OBJC_IVAR_$_DDLogMessage._context", referenced from:
      -[TSDBLogEntry initWithLogMessage:] in TSLocationManager(TSDBLogger.o)
  "_OBJC_IVAR_$_DDAbstractDatabaseLogger._saveThreshold", referenced from:
      -[TSDBLogger initWithLogDirectory:] in TSLocationManager(TSDBLogger.o)
  "_OBJC_CLASS_$_DDTTYLogger", referenced from:
      objc-class-ref in TSLocationManager(TSLog.o)
  "_OBJC_CLASS_$_NativeScript", referenced from:
      objc-class-ref in main.o
     (maybe you meant: _OBJC_CLASS_$_NativeScriptEmbedder)
  "_OBJC_METACLASS_$_DDAbstractDatabaseLogger", referenced from:
      _OBJC_METACLASS_$_TSDBLogger in TSLocationManager(TSDBLogger.o)
  "_OBJC_CLASS_$_DDAbstractDatabaseLogger", referenced from:
      _OBJC_CLASS_$_TSDBLogger in TSLocationManager(TSDBLogger.o)
  "_OBJC_IVAR_$_DDAbstractLogger._logFormatter", referenced from:
      -[TSDBLogger db_log:] in TSLocationManager(TSDBLogger.o)
  "_OBJC_IVAR_$_DDLogMessage._message", referenced from:
      -[TSLogFormatter formatLogMessage:] in TSLocationManager(TSLogFormatter.o)
      -[TSDBLogEntry initWithLogMessage:] in TSLocationManager(TSDBLogger.o)
  "_OBJC_IVAR_$_DDLogMessage._tag", referenced from:
      -[TSLogFormatter formatLogMessage:] in TSLocationManager(TSLogFormatter.o)
  "_OBJC_IVAR_$_DDLogMessage._function", referenced from:
      -[TSLogFormatter formatLogMessage:] in TSLocationManager(TSLogFormatter.o)
  "_OBJC_IVAR_$_DDAbstractDatabaseLogger._maxAge", referenced from:
      -[TSDBLogger getLog] in TSLocationManager(TSDBLogger.o)
      -[TSDBLogger db_delete] in TSLocationManager(TSDBLogger.o)
  "_OBJC_CLASS_$_DDLog", referenced from:
      objc-class-ref in TSLocationManager(TSCurrentPositionRequest.o)
      objc-class-ref in TSLocationManager(DatabaseQueue.o)
      objc-class-ref in TSLocationManager(TSConfig.o)
      objc-class-ref in TSLocationManager(LocationAuthorization.o)
      objc-class-ref in TSLocationManager(GeofenceDAO.o)
      objc-class-ref in TSLocationManager(TSHttpService.o)
      objc-class-ref in TSLocationManager(TSGeofenceManager.o)
      ...
  "_OBJC_CLASS_$_Config", referenced from:
      objc-class-ref in main.o
  "_OBJC_IVAR_$_DDLogMessage._flag", referenced from:
      -[TSLogFormatter formatLogMessage:] in TSLocationManager(TSLogFormatter.o)
      -[TSDBLogEntry initWithLogMessage:] in TSLocationManager(TSDBLogger.o)
  "_TNSInitializeLiveSync", referenced from:
      _main in main.o
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by farfromrefug** [comment]
@mrwrighty what is all those. I dont think those symbols come from Mapbox. Must be another 3rd party plugin

**Comment by mrwrighty** [comment]
I had nativescript-background-geolocation-lt installed so have removed that and now get

Undefined symbols for architecture i386:
  "_OBJC_CLASS_$_Config", referenced from:
      objc-class-ref in main.o
  "_OBJC_CLASS_$_NativeScript", referenced from:
      objc-class-ref in main.o
     (maybe you meant: _OBJC_CLASS_$_NativeScriptEmbedder)
  "_TNSInitializeLiveSync", referenced from:
      _main in main.o
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by farfromrefug** [comment]
@mrwrighty can you try forcing Mapbox version to 5 using something like this https://github.com/nativescript-community/ui-mapbox/blob/master/demo/app/App_Resources/iOS/Podfile

**Comment by mrwrighty** [comment]
Ok pod file now contains pod 'Mapbox-iOS-SDK', '~> 5.1.1' but getting the same error.

**Comment by farfromrefug** [comment]
@mrwrighty and the error is gone if you remove mapbox plugin?

**Comment by mrwrighty** [comment]
Yes removing the plugin and the app builds and installs on simulator.

**Comment by mrwrighty** [comment]
OK good news it looks like some legacy file were left behind after setting the pod file to pod 'Mapbox-iOS-SDK', '~> 5.1.1'. ns clean and a rebuild now works.

**Comment by adideas** [comment]
HI !

Here is what helped me 
- XCODE 13.3.1
- NativeScript 8.0.2 cli
- Platform IOS "6.5.2"

STEP 1 (build.xcconfig)

```
// xcode 13
EXCLUDED_ARCHS__EFFECTIVE_PLATFORM_SUFFIX_simulator__NATIVE_ARCH_64_BIT_x86_64=arm64 arm64e armv7 armv7s armv6 armv8
EXCLUDED_ARCHS=$(inherited)
$(EXCLUDED_ARCHS__EFFECTIVE_PLATFORM_SUFFIX_$(EFFECTIVE_PLATFORM_SUFFIX)__NATIVE_ARCH_64_BIT_$(NATIVE_ARCH_64_BIT))

IPHONEOS_DEPLOYMENT_TARGET = 12.0
```


STEP 2 (Podfile)

```
pod 'CocoaAsyncSocket'

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
      config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
      config.build_settings['CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER'] ='NO'
      config.build_settings['ONLY_ACTIVE_ARCH'] = 'YES'
    end
  end
end

IPHONEOS_DEPLOYMENT_TARGET = 12.0
```
give me a star thanks

**Comment by RemiKalbe** [comment]
Doesn't work for me @adideas
